VirtualMachineError: Out of space in CodeCache for method handle intrinsic
Backport-of: cd2182a9967917e733e486d918e9aeba3bd35ee8
(cherry picked from commit 82790b03da58d812e6067e12d66424fa32252dc4)
Change-Id: I4de29cf5201e1bd33b8fb4371e1d019a23f2c5b1